{{- if eq .Values.deploy.node true }}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: baremetal-csi-node
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: baremetal-csi-node
  template:
    metadata:
      labels:
        app: baremetal-csi-node
        app.kubernetes.io/name: csi-baremetal
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '{{ .Values.node.metrics.port }}'
        prometheus.io/path: '{{ .Values.node.metrics.path }}'
    spec:
      {{- if or (.Values.nodeSelector.key) (.Values.nodeSelector.value)}}
      nodeSelector:
        {{.Values.nodeSelector.key}}: {{.Values.nodeSelector.value}}
      {{- end }}
      hostIPC: True
      serviceAccountName: csi-node-sa
      terminationGracePeriodSeconds: 10
      containers:
      # ********************** DRIVER-REGISTRAR sidecar container definition **********************
      - name: csi-node-driver-registrar
        image: {{- if .Values.env.test }} csi-node-driver-registrar:{{ .Values.nodeDriverRegistrar.image.tag }}
               {{- else }} {{ .Values.global.registry }}/csi-node-driver-registrar:{{ .Values.nodeDriverRegistrar.image.tag }}
               {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--v=5"
          - "--csi-address=$(ADDRESS)"
          - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm -rf /registration/baremetal-csi /registration/baremetal-csi-reg.sock"]
        env:
          - name: ADDRESS
            value: /csi/csi.sock
          - name: DRIVER_REG_SOCK_PATH
            value: /var/lib/kubelet/plugins/baremetal-csi/csi.sock
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        volumeMounts:
          - name: csi-socket-dir
            mountPath: /csi
          - name: registration-dir
            mountPath: /registration
      # ********************** baremetal-csi-node container definition **********************
      - name: node
        image: {{- if .Values.env.test }} baremetal-csi-plugin-node:{{ default .Values.image.tag .Values.node.image.tag }}
               {{- else }} {{ .Values.global.registry }}/baremetal-csi-plugin-node:{{ default .Values.image.tag .Values.node.image.tag }}
              {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - --csiendpoint=$(CSI_ENDPOINT)
          - --nodename=$(KUBE_NODE_NAME)
          - --namespace=$(NAMESPACE)
          - --extender={{ .Values.feature.extender }}
          - --usenodeannotation={{ .Values.feature.usenodeannotation }}
          - --loglevel={{ .Values.log.level }}
          - --metrics-address=:{{ .Values.node.metrics.port }}
          - --metrics-path={{ .Values.node.metrics.path }}
          {{- if .Values.logReceiver.create  }}
          - --logpath=/var/log/csi.log
          {{- end }}
          {{- if .Values.node.grpc.client.drivemgr.endpoint }}
          - --drivemgrendpoint={{ .Values.node.grpc.client.drivemgr.endpoint }}
        {{- end }}
        ports:
          {{- if .Values.drivemgr.grpc.server.port }}
          - containerPort: {{ .Values.drivemgr.grpc.server.port }}
          {{- end }}
          - name: liveness-port
            containerPort: 9808
            protocol: TCP
          {{- if .Values.node.metrics.port }}
          - name: metrics
            containerPort: {{ .Values.node.metrics.port }}
            protocol: TCP
          {{- end }}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: liveness-port
          initialDelaySeconds: 300
          timeoutSeconds: 3
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["/health_probe", "-addr=:{{ .Values.node.grpc.server.port }}"]
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 3
          failureThreshold: 100
        env:
          - name: CSI_ENDPOINT
            value: unix:///csi/csi.sock
          - name: LOG_FORMAT
            value: {{ .Values.log.format }}
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        securityContext:
          privileged: true
        volumeMounts:
        - name: logs
          mountPath: /var/log
        - name: host-dev
          mountPath: /dev
        - name: host-sys
          mountPath: /sys
        - name: host-run-udev
          mountPath: /run/udev
        - name: host-run-lvm
          mountPath: /run/lvm
        - name: host-run-lock
          mountPath: /run/lock
        - name: csi-socket-dir
          mountPath: /csi
        - name: mountpoint-dir
          mountPath: /var/lib/kubelet/pods
          mountPropagation: "Bidirectional"
        - name: csi-path
          mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
          mountPropagation: "Bidirectional"
        {{- if .Values.env.mountHostRoot }}
        - name: host-root
          mountPath: /hostroot
          mountPropagation: "HostToContainer"
        {{- end }}
        {{- if eq .Values.alerts.deployConfig true }}
        - name: alert-config
          mountPath: /etc/config
        {{- end }}
      # ********************** baremetal-csi-drivemgr container definition **********************
      - name: drivemgr
        image: {{- if .Values.env.test }} baremetal-csi-plugin-{{ .Values.drivemgr.type }}:{{ default .Values.image.tag .Values.drivemgr.image.tag }}
               {{- else }} {{ .Values.global.registry }}/baremetal-csi-plugin-{{ .Values.drivemgr.type }}:{{ default .Values.image.tag .Values.drivemgr.image.tag }}
               {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # if halOverride true it means we need to use CM, but e2e doesn't support CM, use iscsi_entrypoint
      {{- if .Values.drivemgr.grpc.server.endpoint }}
        args:
          - --loglevel={{ .Values.log.level }}
          - --drivemgrendpoint={{ .Values.drivemgr.grpc.server.endpoint }}
        {{- if eq .Values.drivemgr.type "loopbackmgr"}}
          - --usenodeannotation={{ .Values.feature.usenodeannotation }}
        {{- end }}
        {{- if .Values.logReceiver.create  }}
          - --logpath=/var/log/drivemgr.log
        {{- end }}
      {{- end }}
        securityContext:
          privileged: true
        env:
        - name: LOG_FORMAT
          value: {{ .Values.log.format }}
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        ports:
        {{- if .Values.drivemgr.grpc.server.port }}
          - containerPort: {{ .Values.drivemgr.grpc.server.port }}
        {{- end }}
        volumeMounts:
        - name: host-dev
          mountPath: /dev
        {{- if eq .Values.drivemgr.deployConfig true }}
        - name: drive-config
          mountPath: /etc/config
        {{- end }}
        {{- if .Values.logReceiver.create  }}
        - name: logs
          mountPath: /var/log/
        {{- end }}
        {{- if eq .Values.drivemgr.type "loopbackmgr"}}
        - name: host-home
          mountPath: /host/home
        {{- end }}
      # Liveness probe sidecar
      - name: liveness-probe
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{- if .Values.env.test  }} livenessprobe:{{ .Values.livenessprobe.image.tag }}
               {{- else }} {{ .Values.global.registry }}/livenessprobe:{{ .Values.livenessprobe.image.tag }}
               {{- end }}
        args:
          - --csi-address=/csi/csi.sock
        volumeMounts:
          - mountPath: /csi
            name: csi-socket-dir
      # Log receiver sidecar
      {{- if .Values.logReceiver.create  }}
      - name: fluentbit-agent
        image: {{ .Values.global.registry }}/{{ .Values.fluentbitAgent.image.name }}:{{ default .Values.tag .Values.fluentbitAgent.image.tag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: logs-config
            mountPath: /fluent-bit/etc
          - name: logs
            mountPath: /var/log/
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
      {{- end }}
      volumes:
      {{- if .Values.logReceiver.create }}
      - name: logs-config
        configMap:
          name: {{ .Release.Name }}-logs-config
      {{- end }}
      - name: logs
        emptyDir: {}
      - name: host-dev
        hostPath:
          path: /dev
          type: Directory
      {{- if eq .Values.drivemgr.type "loopbackmgr"}}
      - name: host-home
        hostPath:
          path: /home
          type: Directory
      {{- end }}
      - name: host-sys
        hostPath:
          path: /sys
          type: Directory
      {{- if .Values.env.mountHostRoot }}
      - name: host-root
        hostPath:
          path: /
          type: Directory
      {{- end }}
      - name: host-run-udev
        hostPath:
          path: /run/udev
          type: Directory
      - name: host-run-lvm
        hostPath:
          path: /run/lvm
          type: Directory
      - name: host-run-lock
        hostPath:
          path: /run/lock
          type: Directory
      - name: csi-socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/baremetal-csi
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: DirectoryOrCreate
      # This volume is where the driver mounts volumes
      - name: mountpoint-dir
        hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
      - name: csi-path
        hostPath:
          path: /var/lib/kubelet/plugins/kubernetes.io/csi
      {{- if eq .Values.drivemgr.deployConfig true }}
      - name: drive-config
        configMap:
          name: loopback-config
      {{- end }}
      {{- if eq .Values.alerts.deployConfig true }}
      - name: alert-config
        configMap:
          name: csi-baremetal-alerts
      {{- end }}
{{- end }}
