{{- if eq .Values.deploy.node true }}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: baremetal-csi-node
spec:
  selector:
    matchLabels:
      app: baremetal-csi-node
  template:
    metadata:
      labels:
        app: baremetal-csi-node
    spec:
      serviceAccountName: csi-node-sa
      containers:
      # ********************** DRIVER-REGISTRAR sidecar container definition **********************
      - name: csi-node-driver-registrar
        image: {{ .Values.global.registry }}/csi-node-driver-registrar:{{ .Values.nodeDriverRegistrar.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--v=5"
          - "--csi-address=$(ADDRESS)"
          - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm -rf /registration/baremetal-csi /registration/baremetal-csi-reg.sock"]
        env:
          - name: ADDRESS
            value: /csi/csi.sock
          - name: DRIVER_REG_SOCK_PATH
            value: /var/lib/kubelet/plugins/baremetal-csi/csi.sock
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        volumeMounts:
          - name: csi-socket-dir
            mountPath: /csi
          - name: registration-dir
            mountPath: /registration
      # ********************** baremetal-csi-node container definition **********************
      - name: node
        {{- if .Values.node.image.tag }}
        image: {{ .Values.global.registry }}/baremetal-csi-plugin-node:{{ .Values.node.image.tag }}
        {{- else }}
        image: {{ .Values.global.registry }}/baremetal-csi-plugin-node:{{ .Values.image.tag }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--csiendpoint=$(CSI_ENDPOINT)"
          - "--nodeid=$(KUBE_NODE_NAME)"
          - "--volumemgrip=$(MY_POD_IP)"
          {{- if .Values.logReceiver.create  }}
          - "--logpath=/var/log/csi.log"
          {{- end }}
        {{- if .Values.node.grpc.client.hwmgr.endpoint }}
          - --hwmgrendpoint={{ .Values.node.grpc.client.hwmgr.endpoint }}
        {{- end }}
        env:
          - name: CSI_ENDPOINT
            value: unix:///csi/csi.sock
          - name: LOG_FORMAT
            value: {{ .Values.log.format }}
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        securityContext:
          privileged: true
        volumeMounts:
        - name: logs
          mountPath: /var/log
        - name: host-dev
          mountPath: /dev
        - name: host-sys
          mountPath: /sys
        - name: host-run-udev
          mountPath: /run/udev
        - name: csi-socket-dir
          mountPath: /csi
        - name: mountpoint-dir
          mountPath: /var/lib/kubelet/pods
          mountPropagation: "Bidirectional"
        ports:
        {{- if .Values.hwmgr.grpc.server.port }}
          - containerPort: {{ .Values.node.grpc.server.port }}
        {{- end }}
      # ********************** baremetal-csi-hwmgr container definition **********************
      # TODO: FABRIC-8595 Replace HWManager to DaemonSet
      - name: hwmgr
        {{- if .Values.hwmgr.image.tag }}
        image: {{ .Values.global.registry }}/baremetal-csi-plugin-hwmgr:{{ .Values.hwmgr.image.tag }}
        {{- else }}
        image: {{ .Values.global.registry }}/baremetal-csi-plugin-hwmgr:{{ .Values.image.tag }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        {{- if .Values.hwmgr.grpc.server.endpoint }}
        - --hwmgrendpoint={{ .Values.hwmgr.grpc.server.endpoint }}
        {{- end }}
        {{- if .Values.logReceiver.create  }}
        - --logpath=/var/log/hwmgr.log
        {{- end }}
        securityContext:
          privileged: true
        env:
        - name: LOG_FORMAT
          value: {{ .Values.log.format }}
        ports:
        {{- if .Values.hwmgr.grpc.server.port }}
          - containerPort: {{ .Values.hwmgr.grpc.server.port }}
        {{- end }}
        {{- if .Values.logReceiver.create  }}
        volumeMounts:
        - name: logs
          mountPath: /var/log/
        {{- end }}
      {{- if .Values.logReceiver.create  }}
      - name: fluentbit-agent
        image: {{ .Values.global.registry }}/{{ .Values.fluentbitAgent.image.repository }}:{{ default .Values.tag .Values.fluentbitAgent.image.tag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: logs-config
            mountPath: /fluent-bit/etc
          - name: logs
            mountPath: /var/log/
      {{- end }}
      volumes:
      {{- if .Values.logReceiver.create }}
      - name: logs-config
        configMap:
          name: {{ .Release.Name }}-logs-config
      {{- end }}
      - name: logs
        emptyDir: {}
      - name: host-dev
        hostPath:
          path: /dev
          type: Directory
      - name: host-sys
        hostPath:
          path: /sys
          type: Directory
      - name: host-run-udev
        hostPath:
          path: /run/udev
          type: Directory
      - name: csi-socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/baremetal-csi
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: DirectoryOrCreate
      # This volume is where the driver mounts volumes
      - name: mountpoint-dir
        hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
{{- end }}
