---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: csi-baremetal-extender-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-baremetal-extender-cr
rules:
  - apiGroups: ["baremetal-csi.dellemc.com"]
    resources: ["volumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["baremetal-csi.dellemc.com"]
    resources: ["availablecapacities"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["baremetal-csi.dellemc.com"]
    resources: ["availablecapacityreservations"]
    verbs: ["get", "list", "create", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-baremetal-extender-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-baremetal-extender-cr
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: csi-baremetal-extender-sa
