---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-baremetal-extender-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-baremetal-extender-cr
rules:
  - apiGroups: ["baremetal-csi.dellemc.com"]
    resources: ["availablecapacities"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-baremetal-extender-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-baremetal-extender-cr
subjects:
  - kind: ServiceAccount
    name: csi-baremetal-extender-sa
