# Docker registry to pull images
global:
  registry: asdrepo.isus.emc.com:9042

env:
 test: false
 mountHostRoot: false

feature:
  extender: false
  usenodeannotation: false

# to deploy on specific nodes kubeclt get nodes -l <key>=<value>
nodeSelector:
  key:
  value:

# logging settings
log:
  format: text
  level: info

# Storage Class name that provisions PVs dynamically
storageClass:
  name: baremetal-csi-sc

# CSI Plugin parameters

# deploy defines which components will be deployed
deploy:
  controller: true
  node: true
  drivemgr: true

image:
  tag: green
  pullPolicy: Always

controller:
  image:
    tag:
  health:
    server:
      port: 9999
  metrics:
    port: 8787
    path: /metrics

node:
  image:
    tag:
  grpc:
    client:
      drivemgr:
        endpoint: tcp://localhost:8888
    server:
      port: 9999
  metrics:
    port: 8787
    path: /metrics

drivemgr:
  type: basemgr
  image:
    tag:
  grpc:
    server:
      endpoint: tcp://localhost:8888
  deployConfig: false
  amountOfLoopDevices: 3
  sizeOfLoopDevices: 101Mi

# CSI Sidecars parameters
provisioner:
  image:
    # if you want to use topology feature (multiple PVCs per pod) you should use v1.2.2
    tag: v1.2.2

attacher:
  # default false because of issue in k8s 1.17/1.18 in attach/detach
  # https://github.com/kubernetes/kubernetes/issues/84169 and 86281`
  deploy: false
  image:
    tag: v1.0.1

nodeDriverRegistrar:
  image:
    tag: v1.0.1-gke.0

livenessprobe:
  image:
    tag: v2.1.0

logReceiver:
  create: false
  #stdout/es if stdout, then fluent bit will print collected logs in stdout, if es, then the output of fluent bit is Elastic Search
  output: stdout #es
  # Valid values for Elasticsearch are "http" and "https"
  # protocol: http

  # Elasticsearch address
  # host: 10.249.234.158

  # Port to use for provided Elasticsearch receiver
  # port: 9200

fluentbitAgent:
  image:
    name: fluent-bit
    tag: shippable

alerts:
  deployConfig: false
  