# Docker registry to pull images
global:
  registry: 10.244.120.194:8085/atlantic  # asdrepo.isus.emc.com:8085/atlantic

env:
 test: false

#format of logs
log:
  format: text
  verbose: true

# Storage Class name that provisions PVs dynamically
storageClass:
  name: baremetal-csi-sc

# CSI Plugin parameters

# deploy defines which components will be deployed
deploy:
  controller: true
  node: true
  drivemgr: true

image:
  tag: green
  pullPolicy: Always

controller:
  image:
    tag:

node:
  image:
    tag:
  grpc:
    client:
      drivemgr:
        endpoint: tcp://localhost:8888
    server:
      port: 9999

drivemgr:
  image:
    repository: baremetal-csi-plugin-drivemgr
    # tag:
  grpc:
    server:
      endpoint: tcp://localhost:8888
  # TODO: switch to another, AK8S-1125
  type: HAL
  deployConfig: false
  amountOfLoopDevices: 3

# CSI Sidecars parameters
provisioner:
  image:
    # if you want to use topology feature (multiple PVCs per pod) you should use v1.2.2
    tag: v1.2.2

attacher:
  image:
    tag: v1.0.1

nodeDriverRegistrar:
  image:
    tag: v1.0.1-gke.0

livenessprobe:
  image:
    tag: v1.1.0

logReceiver:
  create: false
  #stdout/es if stdout, then fluent bit will print collected logs in stdout, if es, then the output of fluent bit is Elastic Search
  output: stdout #es
  # Valid values for Elasticsearch are "http" and "https"
  # protocol: http

  # Elasticsearch address
  # host: 10.249.234.158

  # Port to use for provided Elasticsearch receiver
  # port: 9200

fluentbitAgent:
  image:
    repository: fluent-bit
    tag: shippable
