apiVersion: v1
kind: ServiceAccount
metadata:
  name: csibm-sa
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csibmnode-controller-cr
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["baremetal-csi.dellemc.com"]
    resources: ["csibmnodes"]
    verbs: ["watch", "get", "list", "create", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csibmnoe-controller-rb
subjects:
  - kind: ServiceAccount
    name: csibm-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csibmnode-controller-cr
  apiGroup: rbac.authorization.k8s.io
