kind: Deployment
apiVersion: apps/v1
metadata:
  name: csibm-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csibm-controller
  template:
    metadata:
      labels:
        app: csibm-controller
    spec:
      serviceAccount: csibm-sa
      terminationGracePeriodSeconds: 10
      containers:
      - name: controller
        image: {{- if .Values.env.test }} baremetal-csi-plugin-csibmnode:{{ .Values.image.tag }}
               {{- else }} {{ .Values.image.registry }}/baremetal-csi-plugin-csibmnode:{{ .Values.image.tag }}
               {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          {{- if or (.Values.nodeSelector.key) (.Values.nodeSelector.value)}}
          - --nodeselector="{{.Values.nodeSelector.key}}:{{.Values.nodeSelector.value}}"
          {{- end }}
          - --namespace=$(NAMESPACE)
          - --loglevel={{ .Values.log.level }}
          - --logformat={{ .Values.log.format }}
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
