
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.2
  creationTimestamp: null
  name: drives.baremetal-csi.dellemc.com
spec:
  group: baremetal-csi.dellemc.com
  names:
    kind: Drive
    listKind: DriveList
    plural: drives
    singular: drive
  scope: ""
  validation:
    openAPIV3Schema:
      description: Drive is the Schema for the drives API kubebuilder:object:generate=false
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            Bay:
              type: string
            Enclosure:
              type: string
            Endurance:
              format: int64
              type: integer
            Firmware:
              type: string
            Health:
              type: string
            IsSystem:
              type: boolean
            LEDState:
              type: string
            NodeId:
              type: string
            PID:
              type: string
            Path:
              description: path to the device. may not be set by drivemgr.
              type: string
            SerialNumber:
              type: string
            Size:
              description: size in bytes
              format: int64
              type: integer
            Slot:
              type: string
            Status:
              type: string
            Type:
              type: string
            UUID:
              type: string
            VID:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
