name: Release Charts

on:
  release:
    types:
      - created

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create issue
        id: create_issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CSI_WF_TOKEN }}
        with:
          filename: .github/release_template.md
          assignees: dell/csi-baremetal
        if: startsWith(github.ref, 'refs/tags/')

      - name: Parse release description
        id: split_description
        uses: jungwinter/split@v2
        with:
          msg: ${{ github.event.release.body }}

      - name: Set versions
        id: versions
        run: |
          component_name_1=`echo "${{ steps.split_description.outputs._0 }}" | tr -d ':'`
          component_name_2=`echo "${{ steps.split_description.outputs._2 }}" | tr -d ':'`
          version_1=`echo "${{ steps.split_description.outputs._1 }}" | tr -d ','`
          echo "::set-output name=${component_name_1}::$version_1"
          echo "::set-output name=${component_name_2}::${{ steps.split_description.outputs._3 }}"

      - name: Trigger release workflow in csi-baremetal-operator repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release Charts
          repo: dell/csi-baremetal-operator
          token: ${{ secrets.CSI_WF_TOKEN }}
          ref: ${{ github.event.release.target_commitish }}
          inputs: |
            { "issue_number": "${{ steps.create_issue.outputs.number }}",
              "csi_version": "${{ steps.versions.outputs.csi_version }}",
              "csi_operator_version": "${{ steps.versions.outputs.csi_operator_version }}",
              "release_tag": "${{ github.event.release.tag_name }}" }
        if: startsWith(github.ref, 'refs/tags/')
